version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: nestjs-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestjs_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/nestjs_db
      JWT_SECRET: dev-secret-change-in-production
      JWT_EXPIRATION: 7d
      REFRESH_TOKEN_SECRET: dev-refresh-secret
      REFRESH_TOKEN_EXPIRATION: 30d
      NODE_ENV: development
      CORS_ORIGIN: http://localhost:3001
      API_VERSION: v1
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npx prisma migrate deploy && npm run start:dev"

volumes:
  postgres_data: